Cookie handling for GOV.UK Chat
alphagov/govuk-fastly pull request #105
Opened 2024-09-04 09:22 UTC by kevindew

Trello: https://trello.com/c/VZsfdz7x/1739-spike-into-configuring-govuk-infrastructure-so-that-we-can-serve-chat-on-wwwgovuk-chat

GOV.UK Chat is going to be hosted on www.gov.uk/chat and will make use of cookies. Therefore we are going to need to alter the VCL so that cookies are not automatically stripped.

For GOV.UK Chat we want the homepage (GET /chat) to be cached so the regex matches only apply to paths within /chat/*.

If a user has a session cookie for chat we want to always pass the message to the server, if they don't have this session cookie it will be safe to strip to cookies where there may.

I wasn't 100% sure about the behaviour of Fastly caching when cookies are set or not, so to avoid any accidental cachings I've set it to pass any responses received from /chat/* that set a cookie.

These changes will need some testing in integration prior to going live.

/cc @rtrinque to fit into your work

2024-09-04 14:57 UTC, samsimpson1 requested changes
This looks good, but I'm doing some structural changes to this repo which will break this PR. I'll fix this PR up once my changes are complete.

2024-09-05 10:12 UTC, kevindew commented
Thanks @samsimpson1 no problem. Are your changes now merged in? It'd be good to give this stuff a test now @rtrinque has merged changes in

2024-09-05 13:06 UTC, samsimpson1 approved these changes
I've made the necessary change for it to work with the new repo layout, please take a look and merge it if you're happy with it.

2024-09-05 13:08 UTC, kevindew commented
That's great - thanks @samsimpson1 ⭐

2024-09-05 13:12 UTC, kevindew commented
@samsimpson1 do you know if there's a way I can test this out on integration before applying it to all envs - just want to establish confidence I've not made a clanging error.

2024-09-05 13:18 UTC, samsimpson1 commented
Each environment has its own TF workspace now so you can apply the change to integration before staging/production

2024-09-05 13:22 UTC, kevindew commented
Ah cool - so after I merge it there won't be an auto apply and I do each environment individually?

2024-09-05 13:26 UTC, samsimpson1 commented
It won't auto-apply anything on merge. Someone will have to approve the changes first in the TFC console.

2024-09-05 14:23 UTC, merged