[DO NOT MERGE] Add PopularTasks AB test
alphagov/govuk-fastly pull request #93
Opened 2024-08-05 13:52 UTC by CodeSonia

## What

[Trello](https://trello.com/c/mcOB0YrA/2748-setup-populartasks-ab-test-100-to-z-for-24-hours-s)

Add the AB test configuration for `PopularTasks` AB test.

Note at this stage we're not sure how many variants there will be - this is just a set-up for when the PA confirms the variants.

## Why

To prepare for the AB test

2024-08-16 15:29 UTC, hannako requested changes
Thanks Sonia!

We now have the revised variants and percentages:
A, B, C, Z
cookie duration 43200 1/2 day
100% to Z remains the same

2024-08-19 08:44 UTC, CodeSonia commented
> Thanks Sonia!
> 
> We now have the revised variants and percentages: A, B, C, Z cookie duration 43200 1/2 day 100% to Z remains the same

This has now been all revised! Thanks Jess for looking at it ☺️

2024-08-19 09:46 UTC, hannako approved these changes
LGTM!

2024-08-22 14:00 UTC, leenagupte approved these changes

2024-08-23 08:50 UTC, merged